name: deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: 12
      - run: npm ci
      - run: scp index.html ${{secrets.YACLOUD_SSH_USER}}@${{secrets.YACLOUD_SSH_IP}} -i {{secrets.YACLOUD_PRIVATE_KEY}}
